[project]
name = "data-vault-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt>=1.0.0.40.0",
    "dbt-postgres>=1.9.0",
]
